In [95]:
import numpy as np
import pandas as pd 
import datetime
from pynytimes import NYTAPI
#pip install --upgrade pynytimes


# Make sure to set parse dates to True so that the dates
# are parsed into datetime.datetime or datetime.date objects
nyt = NYTAPI(
    key="t8vriKxFjaET2Qo7jSVKTsBYVXSeGw0h",  # Get your API Key at https://developer.nytimes.com
    parse_dates=True,
)


def nyt_searcher(n_results,start_date,):
    'number of results,start date (in datetime.date format)'
    # add way to do more then one if n_results >2010 
    # number of searches with 2k results each 
    num_2k_searches = n_results//2000
    #number of searches left after doing all 2k searches
    num_last_search = n_results%2000
    # initial starting date 
    last_date = start_date
    # initialize empty list to store results 
    results =[]
    #do num_2k_searches
    for i in range(num_2k_searches):
        articles = nyt.article_search(
            results= 2000, # 2k searchs each run 
            dates= {"end":last_date}, # gets updated each iteration
            options = {"sort": "relevance",
            "sources": [
            "New York Times",
            "AP",
            "Reuters",
            "International Herald Tribune"
            ],
            "news_desk": [
            "Business"
            ],
            "type_of_material": [
                "News Analysis", "Summary", "Text" ,"News", "List", "Interview", "Article"
            ]
        }
)
        results.append(articles) # add articles from this run to results list
        articles_df = pd.DataFrame(articles) # prob better way to do this but this works for now
        num_articles= len(articles) 
        last_date = articles_df['pub_date'][num_articles] # assuming they come in order...
        last_date= datetime.datetime.date(last_date) # convert to datetime.date for usage in next iteration
    # run last search for num_last_search results if greater then 0 
    if num_last_search !=0: 
        last_articles = nyt.article_search(
                results= num_last_search,
                dates= {"end":last_date},
                options = {"sort": "relevance",
                "sources": [
                "New York Times",
                "AP",
                "Reuters",
                "International Herald Tribune"
                ],
                "news_desk": [
                "Business"
                ],
                "type_of_material": [
                    "News Analysis", "Summary", "Text" ,"News", "List", "Interview", "Article"
                ]
            }
    ) 
        # add last_articles to results list 
        results.append(last_articles)
    #BELOW SECTION MAY NEED WORK ???
    flatten_results = [val for sublist in results for val in sublist] #results is returning a double listed dictionary value and this reduces it to a single list that we can create a dataframe out of
    
    # if less 2000 posts in search results
    if len(results)==1:
        results_df= pd.DataFrame(flatten_results)
    else: 
        #make list of dictionaries into dataframe 
        results_df = pd.concat(results,sort=False)
        results_df= pd.DataFrame(flatten_results)
    #drop duplicates 
    #results_df.drop_duplicates(inplace=True)
    return results_df

In [122]:
# testing function 
test_df_12 = nyt_searcher(100,datetime.date(2011, 1, 4))

/Users/plarkin/opt/anaconda3/lib/python3.8/site-packages/pynytimes-0.7.0-py3.8.egg/pynytimes/api.py:766: UserWarning: Asking for a lot of results, because of rate limits it can take a while.

In [123]:
test_df_12.tail(1)

,abstract,web_url,snippet,lead_paragraph,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,subsection_name,byline,type_of_material,_id,word_count,uri,print_section,print_page
99,Shoppers spent more this holiday season than a...,https://www.nytimes.com/2010/12/28/business/28...,Shoppers spent more this holiday season than a...,Americans are splurging as though it’s 2007 ag...,The New York Times,"[{'rank': 0, 'subtype': 'jumbo', 'caption': No...","{'main': 'Retail Sales Rebound, Beating Foreca...","[{'name': 'subject', 'value': 'Shopping and Re...",2010-12-27 23:38:59+00:00,article,Business,Business Day,NaN,"{'original': 'By Stephanie Clifford', 'person'...",News,nyt://article/54045c51-f140-5919-94d8-658467bb...,1040,nyt://article/54045c51-f140-5919-94d8-658467bb...,B,1

In [120]:
test_df_11.tail(1)

,abstract,web_url,snippet,lead_paragraph,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name,print_section,print_page
299,The bank agreed to pay more than $2.5 billion ...,https://www.nytimes.com/2011/01/04/business/04...,The bank agreed to pay more than $2.5 billion ...,Bank of America announced on Monday that it ha...,The New York Times,[],{'main': 'Bank of America Buys Back $2.5 Billi...,"[{'name': 'subject', 'value': 'Company Reports...",2011-01-03 12:45:25+00:00,article,Business,Business Day,"{'original': 'By Ben Protess and Eric Dash', '...",News,nyt://article/9b605a3b-41dc-5087-a860-b5ab5f90...,714,nyt://article/9b605a3b-41dc-5087-a860-b5ab5f90...,NaN,B,3

In [115]:
test_df_10.tail(1)

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,subsection_name,byline,type_of_material,_id,word_count,uri
1799,The solar permit process varies widely from mu...,https://www.nytimes.com/2011/01/20/business/en...,The solar permit process varies widely from mu...,"Ken Button, the president of Verengo Solar Plu...",B,1,The New York Times,"[{'rank': 0, 'subtype': 'xlarge', 'caption': N...","{'main': 'Solar Firms Frustrated by Permits', ...","[{'name': 'subject', 'value': 'Solar Energy', ...",2011-01-20 01:54:23+00:00,article,Business,Business Day,Energy & Environment,"{'original': 'By Tom Zeller Jr', 'person': [{'...",News,nyt://article/aedf8f78-9c01-5b8c-8c18-a20faacb...,1104,nyt://article/aedf8f78-9c01-5b8c-8c18-a20faacb...

In [113]:
test_df_9.tail(1)

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
1799,The cases question whether the Madoff firm’s t...,https://www.nytimes.com/2011/05/06/business/06...,The cases question whether the Madoff firm’s t...,Two cases tied to efforts to liquidate Bernard...,B,9,The New York Times,"[{'rank': 0, 'subtype': 'blog480', 'caption': ...",{'main': 'Two Madoff Cases Reach Federal Court...,"[{'name': 'persons', 'value': 'Picard, Irving ...",2011-05-06 01:21:47+00:00,article,Business,Business Day,"{'original': 'By Bloomberg News', 'person': [{...",News,nyt://article/bf9d3251-28e6-510f-8dce-155126ba...,409,nyt://article/bf9d3251-28e6-510f-8dce-155126ba...,NaN

In [111]:
test_df_8.tail()

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
1795,"Kathleen Barnes joined Kelliher Samets Volk, B...",https://www.nytimes.com/2011/08/22/business/me...,"Kathleen Barnes joined Kelliher Samets Volk, B...","Kathleen Barnes joined Kelliher Samets Volk, B...",NaN,NaN,The New York Times,[],{'main': 'Accounts and People of Note in the A...,"[{'name': 'subject', 'value': 'Appointments an...",2011-08-22 17:50:31+00:00,article,Business,Business Day,"{'original': 'By The New York Times', 'person'...",News,nyt://article/57a87450-005d-53a3-927e-2e77cda2...,1222,nyt://article/57a87450-005d-53a3-927e-2e77cda2...,Media
1796,Red Lobster’s new campaign connects restaurant...,https://www.nytimes.com/2011/08/22/business/me...,Red Lobster’s new campaign connects restaurant...,Q. (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-08-22 17:50:29+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/a7d0366d-7411-5eed-b1e4-63166bf3...,238,nyt://article/a7d0366d-7411-5eed-b1e4-63166bf3...,Media
1797,"In their first joint development project, the ...",https://www.nytimes.com/2011/08/23/business/fo...,"In their first joint development project, the ...","DEARBORN, Mich. — Ford Motor Company and Toyot...",B,3,The New York Times,"[{'rank': 0, 'subtype': 'xlarge', 'caption': N...",{'main': 'Ford and Toyota to Work Together on ...,"[{'name': 'organizations', 'value': 'Ford Moto...",2011-08-22 16:51:26+00:00,article,Business,Business Day,"{'original': 'By Nick Bunkley', 'person': [{'f...",News,nyt://article/791bab91-f51a-528d-9909-267edd07...,570,nyt://article/791bab91-f51a-528d-9909-267edd07...,NaN
1798,Highlights from the DealBook newsletter.,https://dealbook.nytimes.com/2011/08/22/mornin...,Highlights from the DealBook newsletter.,"Star Analysts Are Back (No Autographs, Please)...",NaN,NaN,The New York Times,[],"{'main': 'Morning Take-Out', 'kicker': 'DealBo...",[],2011-08-22 13:57:58+00:00,article,Business,Business Day,"{'original': 'By Dealbook', 'person': [{'first...",News,nyt://article/a14293a8-97a9-56c2-8982-26af6a74...,1899,nyt://article/a14293a8-97a9-56c2-8982-26af6a74...,NaN
1799,A slump in Germany and France raises the possi...,https://www.nytimes.com/2011/08/23/business/gl...,A slump in Germany and France raises the possi...,BERLIN — It is not hard to come up with reason...,NaN,NaN,International Herald Tribune,[],{'main': 'Last Bulwark of Euro Could Be Totter...,[],2011-08-22 12:55:09+00:00,article,Business,Business Day,"{'original': 'By NOAH BARKIN | REUTERS', 'pers...",News,nyt://article/85c25116-b281-5966-a98c-f64c1be5...,732,nyt://article/85c25116-b281-5966-a98c-f64c1be5...,Global Business

In [109]:
test_df_7.tail(1)

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
1799,A group dedicated to preventing suicide among ...,https://www.nytimes.com/2011/12/05/business/me...,A group dedicated to preventing suicide among ...,An organization that provides young Americans ...,NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'jumbo', 'caption': No...","{'main': 'New Endeavor for Trevor Project', 'k...","[{'name': 'subject', 'value': 'Advertising and...",2011-12-05 18:38:52+00:00,article,Business,Business Day,"{'original': 'By Stuart Elliott', 'person': [{...",News,nyt://article/80e1d99f-73e3-5582-bc94-a726829c...,1320,nyt://article/80e1d99f-73e3-5582-bc94-a726829c...,Media

In [107]:
test_df_6.tail(1)

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,subsection_name,byline,type_of_material,_id,word_count,uri
1799,Anniversary campaigns are part of a trend that...,https://www.nytimes.com/2012/04/10/business/me...,Anniversary campaigns are part of a trend that...,IF Madison Avenue had its own hit parade or Ho...,B,2,The New York Times,"[{'rank': 0, 'subtype': 'xlarge', 'caption': N...",{'main': 'Brands Cheer Their Virtues With Anni...,"[{'name': 'subject', 'value': 'Emotions', 'ran...",2012-04-10 00:03:23+00:00,article,Business,Business Day,Media,"{'original': 'By Stuart Elliott', 'person': [{...",News,nyt://article/0bb37ae3-9a7c-5f55-9999-3277c56b...,921,nyt://article/0bb37ae3-9a7c-5f55-9999-3277c56b...

In [105]:
test_df_5.tail(1)

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,subsection_name,byline,type_of_material,_id,word_count,uri
1799,"Sonu Shivdasani is chief executive of Soneva, ...",https://www.nytimes.com/2012/08/20/business/gl...,"Sonu Shivdasani is chief executive of Soneva, ...",Sonu Shivdasani is chief executive of Soneva...,NaN,NaN,International Herald Tribune,[],"{'main': 'Language Can Be the Key to Results',...","[{'name': 'subject', 'value': 'Executives and ...",2012-08-19 11:21:08+00:00,article,Business,Business Day,Global Business,"{'original': 'By Sonia Kolesnikov-Jessop', 'pe...",News,nyt://article/4dc1d4e2-0597-5b71-acdf-b0cb0c48...,982,nyt://article/4dc1d4e2-0597-5b71-acdf-b0cb0c48...

In [103]:
test_df_4.tail(2)

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
1798,Wall Street ended its first day of trading in ...,https://www.nytimes.com/2013/01/03/business/da...,Wall Street ended its first day of trading in ...,Wall Street cheered an agreement that ended th...,B,9,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'Big Gains on Wall Street After the F...,"[{'name': 'persons', 'value': 'Popper, Nathani...",2013-01-02 22:43:37+00:00,article,Business,Business Day,"{'original': 'By Nathaniel Popper', 'person': ...",News,nyt://article/45e47cbc-692b-5ebf-aecb-8945f135...,854,nyt://article/45e47cbc-692b-5ebf-aecb-8945f135...,NaN
1799,"Task lists, special calendars and social apps ...",https://www.nytimes.com/2013/01/03/technology/...,"Task lists, special calendars and social apps ...",I’ve never really made New Year’s resolutions ...,B,6,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'Tech Reminders for Keeping Those New...,"[{'name': 'subject', 'value': 'Mobile Applicat...",2013-01-02 21:09:44+00:00,article,Business,Technology,"{'original': 'By Kit Eaton', 'person': [{'firs...",News,nyt://article/7b848e45-76cd-5fba-b60e-d7c99553...,823,nyt://article/7b848e45-76cd-5fba-b60e-d7c99553...,Personal Tech

In [101]:
test_df_3.tail()

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
1795,"British business, which has a vital interest i...",https://www.nytimes.com/2013/05/06/business/gl...,"British business, which has a vital interest i...",The UK Independence Party will not come close ...,NaN,NaN,International Herald Tribune,[],{'main': 'Britain’s Conservatives Squeezed by ...,"[{'name': 'glocations', 'value': 'Great Britai...",2013-05-05 09:13:48+00:00,article,Business,Business Day,"{'original': 'By Hugo Dixon | Reuters', 'perso...",News,nyt://article/1288df31-e69e-5339-8e56-eb989d0a...,937,nyt://article/1288df31-e69e-5339-8e56-eb989d0a...,Global Business
1796,A new analysis finds the current Supreme Court...,https://www.nytimes.com/2013/05/05/business/pr...,A new analysis finds the current Supreme Court...,"NOT long after 10 a.m. on March 27, a restless...",BU,1,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'Corporations Find a Friend in the Su...,"[{'name': 'organizations', 'value': 'Supreme C...",2013-05-04 21:52:10+00:00,article,Business,Business Day,"{'original': 'By Adam Liptak', 'person': [{'fi...",News,nyt://article/706e0db3-3cdf-5d1a-b213-59ec4132...,2652,nyt://article/706e0db3-3cdf-5d1a-b213-59ec4132...,NaN
1797,College graduates are the only group that has ...,https://www.nytimes.com/2013/05/04/business/co...,College graduates are the only group that has ...,Is college worth it? Given the growing price t...,B,1,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'College Graduates Fare Well in Jobs ...,"[{'name': 'subject', 'value': 'Colleges and Un...",2013-05-04 01:09:48+00:00,article,Business,Business Day,"{'original': 'By Catherine Rampell', 'person':...",News,nyt://article/d9414fa0-36cb-56e9-8e10-3115f335...,1014,nyt://article/d9414fa0-36cb-56e9-8e10-3115f335...,NaN
1798,"The drug pairs Merck’s Zetia, which lowers low...",https://www.nytimes.com/2013/05/04/business/fd...,"The drug pairs Merck’s Zetia, which lowers low...",The Food and Drug Administration approved on F...,B,4,The New York Times,[],{'main': 'Drug to Cut Cholesterol Is Approved ...,"[{'name': 'persons', 'value': 'Thomas, Katie',...",2013-05-04 00:49:50+00:00,article,Business,Business Day,"{'original': 'By Katie Thomas', 'person': [{'f...",News,nyt://article/652e5389-f054-5e72-9f42-f3488c00...,474,nyt://article/652e5389-f054-5e72-9f42-f3488c00...,NaN
1799,Activist shareholders had called for the 78-ye...,https://www.nytimes.com/2013/05/04/business/oc...,Activist shareholders had called for the 78-ye...,"Conceding to a shareholder revolt, Occidental ...",B,4,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'Occidental Chairman Agrees to Step D...,"[{'name': 'persons', 'value': 'Krauss, Cliffor...",2013-05-03 21:06:49+00:00,article,Business,Business Day,"{'original': 'By Clifford Krauss', 'person': [...",News,nyt://article/5fce7673-194d-5dc4-83b6-6b69f7bb...,702,nyt://article/5fce7673-194d-5dc4-83b6-6b69f7bb...,NaN

In [99]:
test_df_2

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
0,"Even with the partial federal shutdown, new-ca...",https://www.nytimes.com/2013/11/02/business/us...,"Even with the partial federal shutdown, new-ca...",DETROIT — The tempo for new-car sales in the U...,B,2,The New York Times,[],{'main': 'Big Gains for Auto Sales Despite a G...,"[{'name': 'subject', 'value': 'Automobiles', '...",2013-11-01 20:35:16+00:00,article,Business,Business Day,"{'original': 'By Jaclyn Trop', 'person': [{'fi...",News,nyt://article/abace18d-0cb4-5cc5-9e18-ad35d89a...,686,nyt://article/abace18d-0cb4-5cc5-9e18-ad35d89a...,NaN
1,With Sebastian Vettel crowned this year’s Form...,https://www.nytimes.com/2013/11/02/automobiles...,With Sebastian Vettel crowned this year’s Form...,Sunday’s Grand Prix of Abu Dhabi —– 17th of th...,NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'For Vettel, No Pressure in Abu Dhabi...","[{'name': 'subject', 'value': 'Automobiles', '...",2013-11-01 19:00:07+00:00,article,Business,Automobiles,"{'original': 'By Leo Levine', 'person': [{'fir...",News,nyt://article/b9835a8c-30b6-59f8-acee-d2c8ddb3...,645,nyt://article/b9835a8c-30b6-59f8-acee-d2c8ddb3...,NaN
2,A year after Hurricane Sandy flooded Brooklyn ...,https://www.nytimes.com/2013/11/01/automobiles...,A year after Hurricane Sandy flooded Brooklyn ...,"When you think of waterfront property, beach h...",NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'Brooklyn Motor Works: From Underwate...,"[{'name': 'subject', 'value': 'Hurricane Sandy...",2013-11-01 18:42:29+00:00,article,Business,Automobiles,"{'original': 'By Benjamin Preston', 'person': ...",News,nyt://article/ba0a0686-78f6-5c98-9190-ad08d911...,902,nyt://article/ba0a0686-78f6-5c98-9190-ad08d911...,NaN
3,When employment statistics are adjusted to acc...,https://www.nytimes.com/2013/11/02/business/ec...,When employment statistics are adjusted to acc...,THE unemployment rate has fallen by nearly thr...,B,3,The New York Times,[],{'main': 'Changes in Labor Force Mask Gains in...,"[{'name': 'subject', 'value': 'United States E...",2013-11-01 18:41:44+00:00,article,Business,Business Day,"{'original': 'By Floyd Norris', 'person': [{'f...",News,nyt://article/d43c1560-39c4-5ee9-b7aa-22cf5175...,714,nyt://article/d43c1560-39c4-5ee9-b7aa-22cf5175...,Economy
4,The Federal Communications Commission has prop...,https://www.nytimes.com/2013/11/02/business/me...,The Federal Communications Commission has prop...,WASHINGTON — The Federal Communications Commis...,B,1,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'F.C.C. Plans Sweeping Changes to Bol...,"[{'name': 'subject', 'value': 'Regulation and ...",2013-11-01 18:19:19+00:00,article,Business,Business Day,"{'original': 'By Edward Wyatt', 'person': [{'f...",News,nyt://article/bd83811d-72f2-5932-80fa-495a546b...,767,nyt://article/bd83811d-72f2-5932-80fa-495a546b...,Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,The Group of 20 summit meeting is expected to ...,https://www.nytimes.com/2013/09/06/business/gl...,The Group of 20 summit meeting is expected to ...,MOSCOW — Many of the leaders of the world’s ri...,B,1,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'Plan at G-20 Is to Tighten Global Ru...,"[{'name': 'organizations', 'value': 'Group of ...",2013-09-06 01:18:43+00:00,article,Business,Business Day,"{'original': 'By Andrew E. Kramer', 'person': ...",News,nyt://article/f4b0429f-f95b-51d1-9cb6-5ea2ab25...,913,nyt://article/f4b0429f-f95b-51d1-9cb6-5ea2ab25...,Global Business
996,A federal court in Washington blocked one serv...,https://www.nytimes.com/2013/09/06/business/me...,A federal court in Washington blocked one serv...,"For the first time in nearly a year, the natio...",NaN,NaN,The New York Times,[],{'main': 'Networks Get a Victory in Court Over...,"[{'name': 'subject', 'value': 'Suits and Litig...",2013-09-06 01:09:06+00:00,article,Business,Business Day,"{'original': 'By Brian Stelter', 'person': [{'...",News,nyt://article/e63b2aff-5130-5099-87ae-64abbefc...,604,nyt://article/e63b2aff-5130-5099-87ae-64abbefc...,Media
997,Europe said it would pare back its law in exch...,https://www.nytimes.com/2013/09/06/business/gl...,Europe said it would pare back its law in exch...,"BRUSSELS — Seeking to end years of acrimony, t...",B,3,The New York Times,[],"{'main': 'Europe Offers U.S. a Deal, Hoping fo...","[{'name': 'persons', 'value': 'Kanter, James',...",2013-09-06 01:02:11+00:00,article,Business,Business Day,"{'original': 'By James Kanter', 'person': [{'f...",News,nyt://article/99a00659-0fa8-5b51-9a2e-61c27523...,911,nyt://article/99a00659-0fa8-5b51-9a2e-61c27523...,Global Business
998,"Line, which has hundreds of millions of users ...",https://www.nytimes.com/2013/09/06/technology/...,"Line, which has hundreds of millions of users ...","TOKYO — Traditionally, Japanese bow when greet...",B,2,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'A Japanese Social App Contacts New S...,"[{'name': 'persons', 'value': 'Pfanner, Eric',...",2013-09-06 00:56:02+00:00,article,Business,Technology,"{'original': 'By Eric Pfanner', 'person': [{'f...",News,nyt://article/ec89a325-e723-56cf-9461-bdd20ef9...,1203,nyt://article/ec89a325-e723-56cf-9461-bdd20ef9...,NaN
999,"David Blech, who was once biotechnology’s top ...",https://www.nytimes.com/2013/09/06/business/da...,"David Blech, who was once biotechnology’s top ...",He was once hailed as the king of biotechnolog...,B,1,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'A Biotech King, Dethroned', 'kicker'...","[{'name': 'persons', 'value': 'Blech, David', ...",2013-09-06 00:38:01+00:00,article,Business,Business Day,"{'original': 'By Andrew Pollack', 'person': [{...",News,nyt://article/8ca86cdf-63f0-50db-b217-d24086dd...,1433,nyt://article/8ca86cdf-63f0-50db-b217-d24086dd...,NaN

In [97]:
test_df

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
0,Judge Edward R. Korman of the Eastern District...,https://www.nytimes.com/2014/01/01/business/ju...,Judge Edward R. Korman of the Eastern District...,The government’s right to search travelers’ el...,B,3,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'District Judge Upholds Government’s ...,"[{'name': 'subject', 'value': 'Search and Seiz...",2013-12-31 23:48:51+00:00,article,Business,Business Day,"{'original': 'By Susan Stellin', 'person': [{'...",News,nyt://article/2b1e823c-a372-5db3-ae95-86f20e4a...,741,nyt://article/2b1e823c-a372-5db3-ae95-86f20e4a...,NaN
1,"Mr. Ravitch, 80, is a lawyer who for several y...",https://www.nytimes.com/2014/01/01/realestate/...,"Mr. Ravitch, 80, is a lawyer who for several y...","Mr. Ravitch, 80, is a lawyer who for several y...",B,5,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Richard Ravitch', 'kicker': None, 'c...","[{'name': 'persons', 'value': 'Ravitch, Richar...",2013-12-31 22:56:18+00:00,article,Business,Real Estate,"{'original': 'By Vivian Marino', 'person': [{'...",Interview,nyt://article/9ae83f7d-6bd4-5d77-88d2-329b0527...,885,nyt://article/9ae83f7d-6bd4-5d77-88d2-329b0527...,Commercial Real Estate
2,City officials hope to bring a disparate jumbl...,https://www.nytimes.com/2014/01/01/realestate/...,City officials hope to bring a disparate jumbl...,PHILADELPHIA — On a desolate North Philadelphi...,B,1,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'Philadelphia Forges Plan to Rebuild ...,"[{'name': 'persons', 'value': 'Hurdle, Jon', '...",2013-12-31 22:48:35+00:00,article,Business,Real Estate,"{'original': 'By Jon Hurdle', 'person': [{'fir...",News,nyt://article/ff1041e2-7171-5842-88fb-f52c5f1f...,1199,nyt://article/ff1041e2-7171-5842-88fb-f52c5f1f...,Commercial Real Estate
3,"College dormitories are booming in Manhattan, ...",https://www.nytimes.com/2014/01/01/realestate/...,"College dormitories are booming in Manhattan, ...",Manhattan may be a bit large to be considered ...,B,4,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'Where 600 College Students Live Abov...,"[{'name': 'persons', 'value': 'Hughes, C J', '...",2013-12-31 21:36:51+00:00,article,Business,Real Estate,"{'original': 'By C. J. Hughes', 'person': [{'f...",News,nyt://article/525c0c66-ca09-5e8f-8609-b7523d73...,1180,nyt://article/525c0c66-ca09-5e8f-8609-b7523d73...,Commercial Real Estate
4,"Pure, a British electronics manufacturer, make...",https://www.nytimes.com/2014/01/02/technology/...,"Pure, a British electronics manufacturer, make...",Two of the biggest tech trends this year were ...,NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'The Marriage of Wireless Speaker and...,"[{'name': 'subject', 'value': 'Speakers (Audio...",2013-12-31 19:37:42+00:00,article,Business,Technology,"{'original': 'By Gregory Schmidt', 'person': [...",News,nyt://article/ac9fb65f-e884-50b8-84f0-20c7e52f...,368,nyt://article/ac9fb65f-e884-50b8-84f0-20c7e52f...,Personal Tech
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"The change, expected before the end of the yea...",https://www.nytimes.com/2013/11/01/business/pa...,"The change, expected before the end of the yea...",WASHINGTON — The days of airline passengers be...,B,1,The New York Times,[],{'main': 'F.A.A. Moves to Ease Electronics Ban...,"[{'name': 'subject', 'value': 'Airlines and Ai...",2013-10-31 15:06:07+00:00,article,Business,Business Day,"{'original': 'By Matthew L. Wald', 'person': [...",News,nyt://article/0d9325bc-05da-55d3-ac46-1374aa68...,968,nyt://article/0d9325bc-05da-55d3-ac46-1374aa68...,NaN
996,Jeep’s soft pet carrier offers pet owners a sa...,https://www.nytimes.com/2013/10/31/automobiles...,Jeep’s soft pet carrier offers pet owners a sa...,Just about anyone with a large dog can appreci...,AU,4,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'A Doggie Bag for Your Jeep', 'kicker...","[{'name': 'subject', 'value': 'Automobiles', '...",2013-10-31 14:00:06+00:00,article,Business,Automobiles,"{'original': 'By Benjamin Preston', 'person': ...",News,nyt://article/0dfd53b6-1053-554c-9b9a-9e4ad3fb...,335,nyt://article/0dfd53b6-1053-554c-9b9a-9e4ad3fb...,NaN
997,Many of the growth plans laid out in June lack...,https://www.nytimes.com/2013/11/01/business/in...,Many of the growth plans laid out in June lack...,HONG KONG — Nearly a year after the Japanese b...,B,8,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'After a Run of Growth, Concern Over ...","[{'name': 'glocations', 'value': 'Japan', 'ran...",2013-10-31 13:51:58+00:00,article,Business,Business Day,"{'original': 'By Bettina Wassener', 'person': ...",News,nyt://article/8a2723f0-70d8-5b4b-88e5-0a2f03c2...,778,nyt://article/8a2723f0-70d8-5b4b-88e5-0a2f03c2...,International Business
998,"The cable company lost 306,000 television subs...",https://www.nytimes.com/2013/11/01/business/me...,"The cable company lost 306,000 television subs...",The CBS blackout in homes with Time Warner Cab...,B,1,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'Time Warner Left Bruised in Fee Batt...,"[{'name': 'persons', 'value': 'Stelter, Brian'...",2013-10-31 12:39:13+00:00,article,Business,Business Day,"{'original': 'By Brian Stelter', 'person': [{'...",News,nyt://article/68cbde2a-6933-5aba-9107-9e8ac6a4...,958,nyt://article/68cbde2a-6933-5aba-9107-9e8ac6a4...,Media
999,The company said the results were positive bec...,https://www.nytimes.com/2013/11/01/business/me...,The company said the results were positive bec...,The New York Times Company reported a quarterl...,B,7,The New York Times,[],"{'main': 'Times Co. Posts a Loss, Hurt by Sale...","[{'name': 'persons', 'value': 'Haughney, Chris...",2013-10-31 12:35:00+00:00,article,Business,Business Day,"{'original': 'By Christine Haughney', 'person'...",News,nyt://article/be9facbc-1911-5936-af4f-40419f4e...,708,nyt://article/be9facbc-1911-5936-af4f-40419f4e...,Media

In [124]:
master_df = pd.concat([test_df, test_df_2,test_df_3, test_df_4,test_df_5,test_df_6,test_df_7,test_df_8,test_df_9,test_df_10, test_df_11, test_df_12])
master_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16800 entries, 0 to 99
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   abstract          16800 non-null  object
 1   web_url           16800 non-null  object
 2   snippet           16800 non-null  object
 3   lead_paragraph    16800 non-null  object
 4   print_section     13467 non-null  object
 5   print_page        13467 non-null  object
 6   source            16800 non-null  object
 7   multimedia        16800 non-null  object
 8   headline          16800 non-null  object
 9   keywords          16800 non-null  object
 10  pub_date          16800 non-null  datetime64[ns, UTC]
 11  document_type     16800 non-null  object
 12  news_desk         16800 non-null  object
 13  section_name      16800 non-null  object
 14  byline            16800 non-null  object
 15  type_of_material  16800 non-null  object
 16  _id               16800 non-null  object
 17  word_count        16800 non-null  int64
 18  uri               16800 non-null  object
 19  subsection_name   9434 non-null   object
dtypes: datetime64[ns, UTC](1), int64(1), object(18)
memory usage: 2.7+ MB

In [126]:
master_df.to_csv('data_2011-2013_PL.csv')