In [2]:
import numpy as np
import pandas as pd 
import datetime

In [5]:
master_df = pd.read_csv('./data_2011-2013_PL.csv')

,Unnamed: 0,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,...,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
0,0,Judge Edward R. Korman of the Eastern District...,https://www.nytimes.com/2014/01/01/business/ju...,Judge Edward R. Korman of the Eastern District...,The government’s right to search travelers’ el...,B,3.0,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'District Judge Upholds Government’s ...,...,2013-12-31 23:48:51+00:00,article,Business,Business Day,"{'original': 'By Susan Stellin', 'person': [{'...",News,nyt://article/2b1e823c-a372-5db3-ae95-86f20e4a...,741,nyt://article/2b1e823c-a372-5db3-ae95-86f20e4a...,NaN

In [10]:
pd.set_option('display.max_columns', 22)
master_df.head(1)

,Unnamed: 0,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
0,0,Judge Edward R. Korman of the Eastern District...,https://www.nytimes.com/2014/01/01/business/ju...,Judge Edward R. Korman of the Eastern District...,The government’s right to search travelers’ el...,B,3.0,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...",{'main': 'District Judge Upholds Government’s ...,"[{'name': 'subject', 'value': 'Search and Seiz...",2013-12-31 23:48:51+00:00,article,Business,Business Day,"{'original': 'By Susan Stellin', 'person': [{'...",News,nyt://article/2b1e823c-a372-5db3-ae95-86f20e4a...,741,nyt://article/2b1e823c-a372-5db3-ae95-86f20e4a...,NaN

In [11]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16800 entries, 0 to 16799
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        16800 non-null  int64
 1   abstract          16800 non-null  object
 2   web_url           16800 non-null  object
 3   snippet           16800 non-null  object
 4   lead_paragraph    16783 non-null  object
 5   print_section     13467 non-null  object
 6   print_page        13467 non-null  float64
 7   source            16800 non-null  object
 8   multimedia        16800 non-null  object
 9   headline          16800 non-null  object
 10  keywords          16800 non-null  object
 11  pub_date          16800 non-null  object
 12  document_type     16800 non-null  object
 13  news_desk         16800 non-null  object
 14  section_name      16800 non-null  object
 15  byline            16800 non-null  object
 16  type_of_material  16800 non-null  object
 17  _id               16800 non-null  object
 18  word_count        16800 non-null  int64
 19  uri               16800 non-null  object
 20  subsection_name   9434 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 2.7+ MB

In [8]:
master_df.isnull().sum()

Unnamed: 0             0
abstract               0
web_url                0
snippet                0
lead_paragraph        17
print_section       3333
print_page          3333
source                 0
multimedia             0
headline               0
keywords               0
pub_date               0
document_type          0
news_desk              0
section_name           0
byline                 0
type_of_material       0
_id                    0
word_count             0
uri                    0
subsection_name     7366
dtype: int64

# Planned Deletions

Planning to delete subsection name. Nearly half do not have a value for that.
Definitely a large portion of duplicates that need to be dropped in snippet and lead paragraph. Not sure best way to go about dropping those that are true duplicates and ones that may still have some info.
Headline may have some value since it is the first thing someone sees, need to figure out way to extract that text
Leaning towards deleting byline. Not sure any info in there could add to our sentiment analysis, possibly keep to have author, maybe we'll see some authors have a greater impact?


At end should check average articles per day.
Reindex

In [44]:
master_df.drop_duplicates(['web_url'],inplace=True)

In [112]:
master_df['abstract'] = master_df['abstract'].map(lambda x: "" if 'Economic reports, corporate earnings and hearings this week in Washington.' in x else x)

In [127]:
master_df.drop(['type_of_material', 'word_count'], axis=1, inplace=True)

In [128]:
master_df.head(1)

,abstract,web_url,snippet,lead_paragraph,headline,pub_date,section_name,byline
0,Judge Edward R. Korman of the Eastern District...,https://www.nytimes.com/2014/01/01/business/ju...,Judge Edward R. Korman of the Eastern District...,The government’s right to search travelers’ el...,{'main': 'District Judge Upholds Government’s ...,2013-12-31 23:48:51+00:00,Business Day,"{'original': 'By Susan Stellin', 'person': [{'..."

In [ ]:
stop, no run this cell
#delete duplicates
#web url has 200 duplicates
master_df.drop_duplicates(['web_url'],inplace=True)

#Planned deletions
#Unnamed is another index, subsection name has too many na's and no relevant info, _id and uri are unique vals but already have web_url, all articles are from news_desk business, all articles are document_type article, keywords is just words with no sentimental words to improve model, multimedia is pics or vids in article that add nothing, source contains info stating NYT or Herald tribune,print_page indicates whether news was printed, print_section indicates what section it was printed in 
master_df.drop(['Unnamed: 0','subsection_name', '_id', 'uri', 'news_desk', 'document_type', 'keywords', 'multimedia', 'source', 'print_page', 'print_section', 'type_of_material’], axis =1, inplace=True)

#drop all these rows
#not dropping duplicates of abstract because there are duplicate abstract titles with unique lead_paragraphs. May need to fill it with empty cell?
master_df.drop(master_df.loc[master_df['abstract']=='Notable properties that have been recently listed for sale, sold or leased.'].index, inplace=True)
master_df.drop(master_df.loc[master_df['abstract']=='Account assignments, executive appointments and miscellaneous news from advertising agencies.'].index, inplace=True)
master_df.drop(master_df.loc[master_df['abstract']=='The following tax-exempt fixed-income issues are scheduled for pricing this week.'].index, inplace=True)
master_df.drop(master_df.loc[master_df['abstract']=='Account assignments, executive appointments and miscellaneous news from the advertising agencies.'].index, inplace=True)
master_df['abstract'] = master_df['abstract'].map(lambda x: "" if 'Highlights from the DealBook newsletter.' in x else x) #blankifying because relevant data in other sections even if this isn't relevant to sentiment
master_df['abstract'] = master_df['abstract'].map(lambda x: "" if 'Economic reports, corporate earnings and hearings this week in Washington.' in x else x)


master_df['snippet'] = master_df['snippet'].map(lambda x: "" if 'Highlights from the DealBook newsletter.' in x else x)

master_df.drop(master_df.loc[master_df['lead_paragraph'] == 'TOP STORIES'].index, inplace=True)

#alltext column creation
master_df['alltext'] = pd.DataFrame(master_df['abstract']+ master_df['lead_paragraph']+ master_df['snippet'])

# adding column for only date from datetime
master_df["Date"] = master_df["pub_date"].map(lambda x: x[0:10])

#setting index to date to merge with stock data
master_df.set_index('Date', inplace = True)

In [173]:
master_df.head(1)

,abstract,web_url,snippet,lead_paragraph,headline,pub_date,section_name,byline,alltext
Date,,,,,,,,,
2013-12-31,Judge Edward R. Korman of the Eastern District...,https://www.nytimes.com/2014/01/01/business/ju...,Judge Edward R. Korman of the Eastern District...,The government’s right to search travelers’ el...,{'main': 'District Judge Upholds Government’s ...,2013-12-31 23:48:51+00:00,Business Day,"{'original': 'By Susan Stellin', 'person': [{'...",Judge Edward R. Korman of the Eastern District...

In [130]:
master_df['abstract'].value_counts().head(20)

                                                                                                                                                                                                          109
A look back on our reporting of the past week’s highs and lows in finance.                                                                                                                                  6
Stanley Ho said through a lawyer that parts of his family had obtained control of his remaining stake in the gambling business without his consent, but he later appeared to contradict the statement.      2
The money will go toward public works projects, small businesses and subsidies for companies that invest in new technology.                                                                                 2
Germany’s finance minister and the United States Treasury secretary expressed confidence in efforts to revamp euro zone economies.                                                                          2
The Pegatron Corporation, which makes iPhones and iPads, acknowledged the recent deaths of young workers, but said it wasn’t because of poor conditions.                                                    2
Benlysta, the first new drug to treat lupus in more than half a century, is the first product approved for its developer, Human Genome Sciences.                                                            2
Despite slow economic growth in the first three months of the year, there were gains in both the industrial and retail sectors in March, according to new data.                                             2
The economy expanded by just 7.7 percent during the first three months of the year, compared with a year earlier, falling short of expectations.                                                            2
Budget cuts mean governments are not willing to pay as much for pills, and new laws in some countries require companies to prove drugs are effective or risk losing coverage.                               2
Economic reports, corporate earnings and hearings this week.                                                                                                                                                2
Weak margins in refining hurt results at the largest European and American oil companies.                                                                                                                   2
Aggressive promotions by online merchants are creating a frenzy among traditional retailers, who count the Friday after Thanksgiving as the busiest shopping day of the year.                               2
The instability could hinder oil shipments, raise energy costs and drive equity prices down.                                                                                                                2
Highlights from the morning newsletter.                                                                                                                                                                     2
Markets fell in Europe and Asia as well amid renewed jitters over Europe’s debt crisis.                                                                                                                     2
Shoppers armed with tablets can use an app to get a sense of how different clothes might mix and match.                                                                                                     2
The government sold almost all of the debt it was offering, but investors received sharply higher interest rates for taking on assets seen as increasingly risky.                                           1
The auto insurer Progressive may have done everything wrong in a lawsuit that became a cause célèbre on social media this week, but there’s a lesson for us all in the details.                             1
Although trillions of dollars in investments in United States Treasury securities are at stake, hand-wringing is only just now starting.                                                                    1
Name: abstract, dtype: int64

In [131]:
master_df['lead_paragraph'].value_counts().head(20)

                                                                                                                                                                                                                    67
Q: (Reader)                                                                                                                                                                                                         37
WASHINGTON                                                                                                                                                                                                          20
A roundup of motoring news from the web:                                                                                                                                                                            16
TOP STORIES                                                                                                                                                                                                         14
Stuart Elliott, the advertising columnist, answers questions from readers each week. Questions can be sent to stuarte@nytimes.com.                                                                                   8
LONDON                                                                                                                                                                                                               6
A roundup of motoring news from around the web:                                                                                                                                                                      6
Accounts                                                                                                                                                                                                             6
This is an excerpt from a series of iPhone applications created by the International Herald Tribune to explain the culture and etiquette of major business centers.                                                  5
                                                                                                                                                                                                                     4
Carl Richards is a certified financial planner in Park City, Utah, and is the director of investor education at the BAM Alliance. His sketches are archived on Your Money.                                           4
Interesting things that Bits reporters and editors found on the Web. More here.                                                                                                                                      3
A roundup of motoring news from around the Web:                                                                                                                                                                      3
Stuart Elliott, the advertising columnist, answers questions from readers each week.                                                                                                                                 3
HOUSTON                                                                                                                                                                                                              3
Here’s what the tech reporters and editors of The New York Times found on the Web.                                                                                                                                   3
SAN FRANCISCO                                                                                                                                                                                                        3
LOS ANGELES                                                                                                                                                                                                          3
KUALA LUMPUR — When a planned 24-hour environmental protest gets under way this Saturday on the outskirts of the coastal Malaysian town of Kuantan, the roll call will include speakers from across the country.     2
Name: lead_paragraph, dtype: int64

In [111]:
master_df.loc[master_df['lead_paragraph']=='Q: (Reader)']

,Unnamed: 0,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
10504,1304,"In a world of smartphones with clocks, why do ...",https://www.nytimes.com/2012/01/09/business/me...,"In a world of smartphones with clocks, why do ...",Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2012-01-09 18:32:15+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/1608c047-7375-52a0-a582-df37e41a...,551,nyt://article/1608c047-7375-52a0-a582-df37e41a...,Media
10861,1661,A puzzling spot for three chains under the TJX...,https://www.nytimes.com/2011/12/12/business/me...,A puzzling spot for three chains under the TJX...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Shopping and Re...",2011-12-12 18:12:14+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/6603460c-c8d4-5f37-afc7-8684b598...,568,nyt://article/6603460c-c8d4-5f37-afc7-8684b598...,Media
11006,6,"The song in the Passat commercial, and a term ...",https://www.nytimes.com/2011/12/05/business/me...,"The song in the Passat commercial, and a term ...",Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Public Relation...",2011-12-05 18:38:49+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/1f75bfdf-ac39-5212-be22-724ced50...,162,nyt://article/1f75bfdf-ac39-5212-be22-724ced50...,Media
11133,133,A reader defends the reputation of Mexican cab...,https://www.nytimes.com/2011/11/28/business/me...,A reader defends the reputation of Mexican cab...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Taxicabs and Ta...",2011-11-28 18:32:20+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/211e5a08-1169-5c59-a357-f5fd51e7...,418,nyt://article/211e5a08-1169-5c59-a357-f5fd51e7...,Media
11256,256,"It’s the “Mexico Taxi Project,” but there are ...",https://www.nytimes.com/2011/11/21/business/me...,"It’s the “Mexico Taxi Project,” but there are ...",Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Public Relation...",2011-11-21 18:50:43+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/3fd1aa34-60c2-508c-af37-296699c4...,394,nyt://article/3fd1aa34-60c2-508c-af37-296699c4...,Media
11391,391,A bank points program changes the soundtrack f...,https://www.nytimes.com/2011/11/14/business/me...,A bank points program changes the soundtrack f...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-11-14 18:31:47+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/5feb54cd-8fde-5302-ab2b-25d15457...,420,nyt://article/5feb54cd-8fde-5302-ab2b-25d15457...,Media
11516,516,"Yes, it’s the Duke. No, it’s not “The Searchers.”",https://www.nytimes.com/2011/11/07/business/me...,"Yes, it’s the Duke. No, it’s not “The Searchers.”",Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-11-07 18:30:46+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/1deb79cb-5feb-5e05-bc0e-04bda223...,383,nyt://article/1deb79cb-5feb-5e05-bc0e-04bda223...,Media
11631,631,Another question on the use of grammar in a co...,https://www.nytimes.com/2011/10/31/business/me...,Another question on the use of grammar in a co...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-10-31 17:40:32+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/34e08cf7-9fec-5fc0-ac0c-d41948f9...,251,nyt://article/34e08cf7-9fec-5fc0-ac0c-d41948f9...,Media
11891,891,Debating the merits of “fake” or outlandish pe...,https://www.nytimes.com/2011/10/17/business/me...,Debating the merits of “fake” or outlandish pe...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-10-17 17:50:36+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/af046397-9385-540f-9b9f-0acfaab2...,619,nyt://article/af046397-9385-540f-9b9f-0acfaab2...,Media
12005,1005,Some may lament the return of the campy commer...,https://www.nytimes.com/2011/10/10/business/me...,Some may lament the return of the campy commer...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-10-10 18:29:10+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/29e6f919-1847-58db-af2e-c2b58691...,594,nyt://article/29e6f919-1847-58db-af2e-c2b58691...,Media
12122,1122,Delta continues its tradition of running spots...,https://www.nytimes.com/2011/10/03/business/me...,Delta continues its tradition of running spots...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-10-03 17:30:32+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/9dae327f-45aa-5904-b53e-d5b8e2ec...,268,nyt://article/9dae327f-45aa-5904-b53e-d5b8e2ec...,Media
12353,1353,Shhh! Advertisers shy from disclosing the loca...,https://www.nytimes.com/2011/09/19/business/me...,Shhh! Advertisers shy from disclosing the loca...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-09-19 17:30:38+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/af27f4fb-64e3-5fe0-8d77-f5175182...,553,nyt://article/af27f4fb-64e3-5fe0-8d77-f5175182...,Media
12469,1469,A recent discussion of advertising-themed film...,https://www.nytimes.com/2011/09/12/business/me...,A recent discussion of advertising-themed film...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-09-12 18:10:30+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/bb1ebb7a-8cc8-517b-8262-94822085...,271,nyt://article/bb1ebb7a-8cc8-517b-8262-94822085...,Media
12567,1567,Should “The Man in the Gray Flannel Suit” be i...,https://www.nytimes.com/2011/09/06/business/me...,Should “The Man in the Gray Flannel Suit” be i...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-09-06 17:50:33+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/1f60724a-2dbd-5914-a91e-0eae7268...,385,nyt://article/1f60724a-2dbd-5914-a91e-0eae7268...,Media
12692,1692,A Prudential billboard leads to a discussion o...,https://www.nytimes.com/2011/08/29/business/me...,A Prudential billboard leads to a discussion o...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-08-29 17:40:20+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/96bd12eb-a4eb-5faf-a107-d5dd3a1a...,401,nyt://article/96bd12eb-a4eb-5faf-a107-d5dd3a1a...,Media
13262,462,A viewer is “mesmerized” by the animated globe...,https://www.nytimes.com/2011/07/25/business/me...,A viewer is “mesmerized” by the animated globe...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-07-25 17:10:28+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/741076b2-7ef2-58f9-bf27-45eb36b4...,558,nyt://article/741076b2-7ef2-58f9-bf27-45eb36b4...,Media
13381,581,It’s a question of whether sound-alike perform...,https://www.nytimes.com/2011/07/18/business/me...,It’s a question of whether sound-alike perform...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-07-18 17:50:31+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/5d5decb4-d617-539c-8ade-5529d53b...,302,nyt://article/5d5decb4-d617-539c-8ade-5529d53b...,Media
13491,691,A spot filmed on the High Line in Manhattan fo...,https://www.nytimes.com/2011/07/11/business/me...,A spot filmed on the High Line in Manhattan fo...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-07-11 17:30:48+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/70094a3a-c750-5eb1-9c5f-58935282...,712,nyt://article/70094a3a-c750-5eb1-9c5f-58935282...,Media
13708,908,A question on a song in the BlackBerry commerc...,https://www.nytimes.com/2011/06/27/business/me...,A question on a song in the BlackBerry commerc...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-06-27 16:17:05+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/e67e92bb-bbc9-561e-874d-ce8361de...,407,nyt://article/e67e92bb-bbc9-561e-874d-ce8361de...,Media
13834,1034,Another question about that Volkswagen CC comm...,https://www.nytimes.com/2011/06/20/business/me...,Another question about that Volkswagen CC comm...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...",[],2011-06-20 17:16:39+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/ffefb3f5-9f7c-5ab7-be5f-57c23945...,658,nyt://article/ffefb3f5-9f7c-5ab7-be5f-57c23945...,Media
13959,1159,Who sings “Lola” in the Diet Pepsi spot?,https://www.nytimes.com/2011/06/13/business/me...,Who sings “Lola” in the Diet Pepsi spot?,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-06-13 18:10:26+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/ca4ede0d-fdfe-5bd6-a19a-63353f32...,362,nyt://article/ca4ede0d-fdfe-5bd6-a19a-63353f32...,Media
14190,1390,A Dunkin’ Donuts commercial raises a point abo...,https://www.nytimes.com/2011/05/31/business/me...,A Dunkin’ Donuts commercial raises a point abo...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-05-31 17:50:28+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/dff9dfb9-62fd-5cec-9732-9678f3a9...,521,nyt://article/dff9dfb9-62fd-5cec-9732-9678f3a9...,Media
14326,1526,Should a talking gecko wear headphones in a ra...,https://www.nytimes.com/2011/05/23/business/me...,Should a talking gecko wear headphones in a ra...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-05-23 17:20:28+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/f17a0f75-0431-5f79-b725-5b2a643f...,646,nyt://article/f17a0f75-0431-5f79-b725-5b2a643f...,Media
14428,1628,Who’s that guy interviewing the Geico gecko in...,https://www.nytimes.com/2011/05/16/business/me...,Who’s that guy interviewing the Geico gecko in...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...",[],2011-05-16 17:00:29+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/30671023-1334-52c0-8340-3be13439...,229,nyt://article/30671023-1334-52c0-8340-3be13439...,Media
14549,1749,The character Keith Stone in the commercials f...,https://www.nytimes.com/2011/05/09/business/me...,The character Keith Stone in the commercials f...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. & A. With Stuart Elliott', 'kicke...","[{'name': 'subject', 'value': 'Advertising and...",2011-05-09 17:20:25+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/e2b734cb-f2b4-5b2a-b14f-9c10e2db...,228,nyt://article/e2b734cb-f2b4-5b2a-b14f-9c10e2db...,Media
14690,90,A reader notices TV car ads running back to ba...,https://www.nytimes.com/2011/05/02/business/me...,A reader notices TV car ads running back to ba...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-05-02 17:00:33+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/c6811e7e-dcae-5297-895f-b6da05de...,225,nyt://article/c6811e7e-dcae-5297-895f-b6da05de...,Media
15023,423,"Yes, you’ll be providing the voice for a duck,...",https://www.nytimes.com/2011/04/11/business/me...,"Yes, you’ll be providing the voice for a duck,...",Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-04-11 16:50:14+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/e143b1ed-f001-5fe1-985d-05e3f67f...,240,nyt://article/e143b1ed-f001-5fe1-985d-05e3f67f...,Media
15137,537,Exploring the echo effect in print and TV spots.,https://www.nytimes.com/2011/04/04/business/me...,Exploring the echo effect in print and TV spots.,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-04-04 17:00:23+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/5cbe05a9-9a9c-57b1-95e9-8a6f7989...,567,nyt://article/5cbe05a9-9a9c-57b1-95e9-8a6f7989...,Media
15400,800,The firing of the comedian Gilbert Gottfried b...,https://www.nytimes.com/2011/03/21/business/me...,The firing of the comedian Gilbert Gottfried b...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. & A. With Stuart Elliott', 'kicke...","[{'name': 'subject', 'value': 'Advertising and...",2011-03-21 17:20:18+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/92057e64-a51e-516b-affe-ca5ff2d5...,610,nyt://article/92057e64-a51e-516b-affe-ca5ff2d5...,Media
15539,939,"It’s not a Hamm, but a Moses, selling Aleve wi...",https://www.nytimes.com/2011/03/14/business/me...,"It’s not a Hamm, but a Moses, selling Aleve wi...",Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-03-14 17:10:21+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/55196586-e14d-5276-ad32-d217df29...,361,nyt://article/55196586-e14d-5276-ad32-d217df29...,Media
15770,1170,"Two questions about Doyle Dane Bernbach, the g...",https://www.nytimes.com/2011/02/28/business/me...,"Two questions about Doyle Dane Bernbach, the g...",Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Online Advertis...",2011-02-28 17:30:35+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/0040e395-d5ea-56e0-825a-e0db2836...,442,nyt://article/0040e395-d5ea-56e0-825a-e0db2836...,Media
15848,1248,What’s behind the use of a Simon and Garfunkel...,https://www.nytimes.com/2011/02/22/business/me...,What’s behind the use of a Simon and Garfunkel...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-02-22 17:40:19+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/30d27808-b310-580e-9ffe-f25e580c...,433,nyt://article/30d27808-b310-580e-9ffe-f25e580c...,Media
16098,1498,Discussing a dancing elephant and a classic ai...,https://www.nytimes.com/2011/02/07/business/me...,Discussing a dancing elephant and a classic ai...,Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-02-07 18:30:28+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/2e720bcf-abb4-55f4-bbe2-6d5d5bb6...,395,nyt://article/2e720bcf-abb4-55f4-bbe2-6d5d5bb6...,Media
16203,1603,"Hey, Mazda, where’s the “Zoom zoom” boy?",https://www.nytimes.com/2011/01/31/business/me...,"Hey, Mazda, where’s the “Zoom zoom” boy?",Q: (Reader),NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'wide', 'caption': Non...","{'main': 'Q. and A. With Stuart Elliott', 'kic...","[{'name': 'subject', 'value': 'Advertising and...",2011-01-31 17:20:17+00:00,article,Business,Business Day,"{'original': None, 'person': [], 'organization...",News,nyt://article/259d6447-aadd-55ce-acc6-d775a357...,271,nyt://article/259d6447-aadd-55ce-acc6-d775a357...,Media

In [116]:
master_df.loc[master_df['abstract']=='Germany’s finance minister and the United States Treasury secretary expressed confidence in efforts to revamp euro zone economies.']

,Unnamed: 0,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,multimedia,headline,keywords,pub_date,document_type,news_desk,section_name,byline,type_of_material,_id,word_count,uri,subsection_name
7630,230,Germany’s finance minister and the United Stat...,https://www.nytimes.com/2012/07/31/business/sp...,Germany’s finance minister and the United Stat...,LONDON — Borrowing costs for Spain and Italy e...,B,3.0,The New York Times,[],{'main': 'Pledges of Euro Support Ease Some Bo...,"[{'name': 'persons', 'value': 'Geithner, Timot...",2012-07-31 04:00:47+00:00,article,Business,Business Day,"{'original': 'By Stephen Castle', 'person': [{...",News,nyt://article/de383be2-4123-5d71-b2a3-6adeac8f...,630,nyt://article/de383be2-4123-5d71-b2a3-6adeac8f...,NaN
7645,245,Germany’s finance minister and the United Stat...,https://www.nytimes.com/2012/07/31/business/gl...,Germany’s finance minister and the United Stat...,LONDON — Borrowing costs for Spain and Italy e...,NaN,NaN,The New York Times,"[{'rank': 0, 'subtype': 'xlarge', 'caption': N...",{'main': 'Pledges of Euro Support Ease Some Bo...,"[{'name': 'subject', 'value': 'Euro (Currency)...",2012-07-30 09:00:35+00:00,article,Business,Business Day,"{'original': 'By Stephen Castle', 'person': [{...",News,nyt://article/f19bf333-11ee-53b4-8a60-b72231c7...,630,nyt://article/f19bf333-11ee-53b4-8a60-b72231c7...,Global Business

In [14]:
master_df['subsection_name'].value_counts()

Global Business                           3423
Media                                     2895
Economy                                    733
Personal Tech                              530
Energy & Environment                       510
Commercial Real Estate                     448
International Business                     313
Entrepreneurship                           116
Arts                                        99
Retirement                                  85
Politics                                    28
Art & Design                                25
Money & Policy                              21
Taxes                                       15
Internet                                    15
Automobiles                                 14
Europe                                      14
Research                                    12
Asset Allocation                            10
Environment                                 10
Companies                                   10
401(k)'s and Similar Plans                   8
Stocks and Bonds                             8
Asia Pacific                                 8
Estate Planning                              7
Mortgages                                    6
Health Insurance                             6
Home Insurance                               6
Brokerage and Bank Accounts                  5
Credit Scores                                5
Financial Planners                           4
Student Loans                                4
Olympics                                     4
Start-Ups                                    3
Annuities                                    3
Life and Disability Insurance                3
Middle East                                  3
Identify Theft                               3
Household Budgeting                          2
Television                                   2
Auto Insurance                               2
Paying for College                           2
Fitness & Nutrition                          1
Small Business Email                         1
Health Guide                                 1
Rugby                                        1
Music                                        1
Individual Retirement Accounts (IRA's)       1
Collectible Cars                             1
DealBook                                     1
Wheels                                       1
Business Computing                           1
New Cars                                     1
Mutual Funds                                 1
Mutual Funds and ETFs                        1
Africa                                       1
Name: subsection_name, dtype: int64

## Bigrams, Trigrams

In [134]:

# imports
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
# from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, plot_confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier


# Import CountVectorizer and TFIDFVectorizer from feature_extraction.text.
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.feature_extraction import text 

#tokenizers
from nltk.tokenize import sent_tokenize, word_tokenize, RegexpTokenizer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import re

In [226]:
draft_df = pd.DataFrame(master_df['alltext'])

In [231]:
draft_df.head(1)

                                                      alltext
Date
2013-12-31  Judge Edward R. Korman of the Eastern District...

In [222]:
draft_df.isnull().sum()

alltext    17
dtype: int64

## stopwords
likely keeping stopwords since our concern in sentiment analysis and stopwords won't effect sentiment

In [244]:
!pip install stop-words
from stop_words import get_stop_words
from nltk.corpus import stopwords

stop_words = list(get_stop_words('en'))         #About 174 stopwords
nltk_words = list(stopwords.words('english')) #About 179 stopwords
stop_words.extend(nltk_words)


def delete_stopwords(words):
    new_phrase = []
    for word in words: # iterate over word_list
        if words.lower().split() not in stop_words:
            new_phrase.append(words.lower())
    return " ".join(new_phrase)
draft_df['alltext'] = draft_df['alltext'].map(lambda x: delete_stopwords(str(x)))
draft_df.head(1)

#still am unable to get rid of the 'of' stopwords, function not working!

KeyboardInterrupt:

In [253]:
#removing stopwords

def delete_stopwords(words):
    if words.lower() not in stop_words:
        return words.lower()
draft_df['alltext'] = draft_df['alltext'].map(lambda x: delete_stopwords(str(x)))

#eliminate the punctuation, URL, and @
draft_df['alltext'] = draft_df['alltext'].map(lambda x: re.sub(r"(@\[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|^rt|http.+?", "", str(x)))
#source: https://monkeylearn.com/blog/text-cleaning/
draft_df.head(5)

                                                      alltext
Date
2013-12-31  judge edward r korman of the eastern district ...
2013-12-31  mr ravitch 80 is a lawyer who for several year...
2013-12-31  city officials hope to bring a disparate jumbl...
2013-12-31  college dormitories are booming in manhattan o...
2013-12-31  pure a british electronics manufacturer makes ...

## Sentiment Analysis

#### Vader Sentiment Analysis

In [256]:
#Adding in Sentiment analysis with designated columns for each output (pos, neg, neu, compound)
%time
analyzer = SentimentIntensityAnalyzer()

draft_df['vd_compound'] = [analyzer.polarity_scores(x)['compound'] for x in draft_df['alltext']]
draft_df['vd_neg'] = [analyzer.polarity_scores(x)['neg'] for x in draft_df['alltext']]
draft_df['vd_neu'] = [analyzer.polarity_scores(x)['neu'] for x in draft_df['alltext']]
draft_df['vd_pos'] = [analyzer.polarity_scores(x)['pos'] for x in draft_df['alltext']]

#took abt 4 hours

#### Flair Sentiment Analysis
source : https://neptune.ai/blog/sentiment-analysis-python-textblob-vs-vader-vs-flair

https://github.com/flairNLP/flair

In [ ]:
%time

!pip install flair

from flair.models import TextClassifier
from flair.data import Sentence

classifier = TextClassifier.load('en-sentiment')
sentence = Sentence('The food was great!')

draft_df['fl_score'] = [classifier.polarity_scores(x)['compound'] for x in draft_df['alltext']]

# classifier.predict(sentence)

# # print sentence with predicted labels
# print('Sentence above is: ', sentence.labels)

#### Textblob Sentiment Analysis
source : https://neptune.ai/blog/sentiment-analysis-python-textblob-vs-vader-vs-flair

https://textblob.readthedocs.io/en/dev/

In [259]:
%time
from textblob import TextBlob

#testimonial = TextBlob()

#draft_df['tb_polarity'] = [testimonial.polarity(x)['polarity'] for x in draft_df['alltext']]
#draft_df['tb_subj'] = [testimonial.sentiment(x)['subjectivity'] for x in draft_df['alltext']]
draft_df['tb_subj'] = draft_df['alltext'].map(lambda words: TextBlob(words).sentiment)
draft_df['tb_polarity'] = draft_df['alltext'].map(lambda words: TextBlob(words).polarity)

#took about 6 hours

In [264]:
draft_df.describe()

           compound           neg           neu           pos   tb_polarity
count  16387.000000  16387.000000  16387.000000  16387.000000  16387.000000
mean       0.222489      0.067688      0.836806      0.095505      0.084125
std        0.942919      0.072312      0.096272      0.076927      0.161710
min       -1.000000      0.000000      0.357000      0.000000     -1.000000
25%       -1.000000      0.000000      0.774000      0.036000      0.000000
50%        1.000000      0.049000      0.843000      0.085000      0.071173
75%        1.000000      0.109000      0.908000      0.142000      0.171429
max        1.000000      0.472000      1.000000      0.643000      1.000000

In [ ]:
draft_df.head(1)

In [ ]:
draft_df.mean()
senti_df.groupby('subreddit').mean().T.plot(kind='bar', stacked=False)
plt.title('Sentiment Analysis of Subreddits')
plt.xlabel('Sentiments')
plt.ylabel('Score');

### CountVectorizer

In [ ]:
cvec = CountVectorizer(stop_words = 'english')
Xc_train = cvec.fit_transform(X_train)
Xc_test = cvec.transform(X_test)


!
#From lesson adding custom stop words
my_words = ['spoon', 'mustard', 'gucci', 'circle jerk', 'tortuga']

stop_words = text.ENGLISH_STOP_WORDS.union(my_words)
CountVectorizer(stopwords = stopwords)

# Let's set a pipeline up with two stages:
# 1. CountVectorizer (transformer)
# 2. Multinomial Naive Bayes (estimator)

pipe = Pipeline([
    ('cvec', CountVectorizer() ),
    ('nb', MultinomialNB())
])

# Search over the following values of hyperparameters:
# Maximum number of features fit: 2000, 3000, 4000, 5000
# Minimum number of documents needed to include token: 2, 3
# Maximum number of documents needed to include token: 90%, 95%
# Check (individual tokens) and also check (individual tokens and 2-grams).

pipe_params = {
    'cvec__max_features': [2000, 3000, 4000, 5000],
    'cvec__min_df': [2, 3],
    'cvec__max_df': [.9, .95],
    'cvec__ngram_range': [(1,1), (1,2)]
}

# Instantiate GridSearchCV.

gs = GridSearchCV(pipe, # what object are we optimizing?
                  pipe_params, # what parameters values are we searching?
              cv =3) # 3-fold cross-validation.
# Fit GridSearch to training data.
gs.fit(X_train, y_train)

# What's the best score?

gs.score(X_train, y_train), gs.score(X_test, y_test)


# Get predictions

preds = gs.predict(X_test)


# Save confusion matrix values
tn, fp, fn, tp = confusion_matrix(y_test, preds).ravel()

# View confusion matrix
plot_confusion_matrix(gs, X_test, y_test, cmap='Blues');

gs.best_params_

## TFIDF

Less likely to use tFIDF since it is looking for relative and rare words across documents to weight them in comparison and that isn't necessarily the goal of our analysis. Weighting words is less important than finding sentiment from counting words.

In [ ]:

# Instantiate the transformer.
tvec = TfidfVectorizer()


# convert training data to dataframe
X_train_df = pd.DataFrame(tvec.fit_transform(X_train).todense(), 
                          columns=tvec.get_feature_names())

# plot top occuring words
X_train_df.sum().sort_values(ascending=False).head(10).plot(kind='barh');

# Set up a pipeline with tf-idf vectorizer and multinomial naive bayes

pipe_tvec = Pipeline([
    ('tvec', TfidfVectorizer()),
    ('nb', MultinomialNB() )
])

# Search over the following values of hyperparameters:
# Maximum number of features fit: 2000, 3000, 4000, 5000
# No stop words and english stop words
# Check (individual tokens) and also check (individual tokens and 2-grams).


pipe_tvec_params = {
    'tvec__max_features': [2_000, 3_000, 4_000, 5_000],
    'tvec__stop_words': [None, 'english'],
    'tvec__ngram_range': [(1,1), (1,2)]
}

# Instantiate GridSearchCV.

gs = GridSearchCV(pipe_tvec, pipe_tvec_params, cv = 3)

# Fit GridSearch to training data.
gs.fit(X_train, y_train)

# What's the best score?

gs.score(X_train, y_train), gs.score(X_test, y_test)


# Get predictions

preds = gs.predict(X_test)


# Save confusion matrix values
tn, fp, fn, tp = confusion_matrix(y_test, preds).ravel()

# View confusion matrix
plot_confusion_matrix(gs, X_test, y_test, cmap='Blues');

gs.best_params_

# Incorporating Stock Data

In [ ]:
#adding in stock data
!pip install yfinance

import yfinance as yf

sp500 = yf.Ticker('^GSPC')
sp500_hist = sp500.history(period='11y')
sp500_hist.to_csv('sp500_1y.csv')
#source: https://opendata.stackexchange.com/questions/18081/free-rest-api-for-daily-end-of-day-sp-500-index

In [ ]:
sp500_hist.head(1)

In [ ]:
sp500_hist.info()

In [ ]:
#averaging multi-day data with single date in order to merge average sentiment with S&P
avrg_date_df=master_df.groupby(['sentiment'](freq='D')).mean()

# Merging Stock and NYT Dataframes

In [ ]:
#merging S&P with NYT data
merge_draft = sp500_hist.join(master_df,)
merge_draft.head(1)